name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: exuanbo/actions-github-lang-chart@v2
        with:
          github_token: ${{ secrets.METRICS_TOKEN }}
          hide_languages: html, css, scss
